# Generated by Django 6.0.2 on 2026-03-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('twilight', 'Twilight'), ('aerial', 'Aerial & Drone'), ('commercial', 'Commercial')], default='interior', max_length=50)),
                ('image_url', models.URLField(help_text='Unsplash URL for remote rendering', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Show on the main home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of feature bullet points (strings)')),
                ('order', models.IntegerField(default=0, help_text='Display order on the booking page')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('real_estate', 'Real Estate'), ('commercial', 'Commercial & Business'), ('add_on', 'Add-On Option')], default='real_estate', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Unsplash URL or remote path', max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional starting price', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=300)),
                ('shoot_date', models.DateField()),
                ('delivery_link', models.URLField(blank=True, help_text='Dropbox or Google Drive link', max_length=500, null=True)),
                ('status', models.CharField(choices=[('editing', 'In Post-Production'), ('delivered', 'Delivered (Ready for Download)'), ('archived', 'Archived')], default='editing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed & Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.package')),
            ],
        ),
    ]
