# Generated by Django 6.0.2 on 2026-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientshoot',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the shoot', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Generated Stripe Checkout Session URL', max_length=1000, null=True),
        ),
    ]
