# Generated by Django 6.0.2 on 2026-03-10 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientshoot_amount_due_clientshoot_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('09:00', '9:00 AM'), ('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='api.photographer'),
        ),
        migrations.CreateModel(
            name='PhotographerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.photographer')),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('photographer', 'date', 'time_slot')},
            },
        ),
    ]
