# Generated by Django 6.0.2 on 2026-03-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookingrequest_shoot_date_bookingrequest_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientshoot',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_shoots', to='api.photographer'),
        ),
    ]
