# Generated by Django 6.0.2 on 2026-03-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientshoot_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Unsplash URL or remote path', max_length=500, null=True),
        ),
    ]
