# Generated by Django 6.0.2 on 2026-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photographer_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientshoot',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled / Upcoming'), ('editing', 'In Post-Production'), ('delivered', 'Delivered (Ready for Download)'), ('archived', 'Archived')], default='scheduled', max_length=20),
        ),
    ]
