# Generated by Django 6.0.2 on 2026-03-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clientshoot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="A unique identifier for the frontend component, e.g., 'home_hero_video'", max_length=100, unique=True)),
                ('title', models.CharField(help_text='A human-readable title for the admin portal', max_length=200)),
                ('url', models.URLField(help_text='The full URL to the media file (e.g., Unsplash, Cloudinary, S3)', max_length=1000)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of where this is used')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
