# Generated by Django 6.0.2 on 2026-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientshoot',
            name='delivery_link',
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='r2_object_key',
            field=models.CharField(blank=True, help_text='Cloudflare R2 Object Key (e.g. orders/{id}/high-res.zip)', max_length=500, null=True),
        ),
    ]
