# Generated by Django 6.0.3 on 2026-03-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_clientshoot_delivery_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Primary SMTP', max_length=100)),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_username', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('email_from_address', models.EmailField(max_length=254)),
                ('email_from_name', models.CharField(default='KC Real Estate Media', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='If active, this configuration will be used for all system emails.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
