# Generated by Django 6.0.2 on 2026-03-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for the template (e.g., 'booking-created')", unique=True)),
                ('title', models.CharField(help_text='Human readable title', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='HTML content with placeholders like {customer_name}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
