# Generated by Django 6.0.2 on 2026-03-15 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('virtual_tour', 'Virtual Tour')], max_length=20)),
                ('url', models.URLField(help_text='Public URL for full size or embedded content', max_length=1000)),
                ('watermarked_url', models.URLField(blank=True, help_text='URL for watermarked/low-res version', max_length=1000, null=True)),
                ('gcs_object_key', models.CharField(blank=True, help_text='Google Cloud Storage object key', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sort order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='api.clientshoot')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
