# Generated by Django 6.0.2 on 2026-03-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientshoot',
            name='baths',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='property_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Listing price of the property', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
