# Generated by Django 6.0.2 on 2026-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_clientshoot_baths_clientshoot_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='equipment',
            field=models.TextField(blank=True, help_text='List of equipment used (e.g. Sony A7IV, RS3 Mini)'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media handles (e.g. {'instagram': 'user', 'website': 'link'})"),
        ),
    ]
