# Generated by Django 6.0.3 on 2026-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_photographer_equipment_photographer_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='True if watermarked/compressed version is ready'),
        ),
    ]
