# Generated by Django 6.0.2 on 2026-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mediaitem_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemedia',
            name='url_before',
            field=models.URLField(blank=True, help_text="Optional 'Before' image for comparison (e.g., for staging or grass edits)", max_length=1000, null=True),
        ),
    ]
