# Generated by Django 6.0.2 on 2026-03-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_globalsettings_clientshoot_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='default_bcc',
            field=models.EmailField(blank=True, help_text='Default BCC address for all automated emails (e.g. admin backup)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='default_cc',
            field=models.EmailField(blank=True, help_text='Default CC address for all automated emails', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='bcc',
            field=models.EmailField(blank=True, help_text='Template-specific BCC address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='cc',
            field=models.EmailField(blank=True, help_text='Template-specific CC address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text body with placeholders like {name}'),
        ),
    ]
