# Generated by Django 6.0.3 on 2026-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_emailconfiguration_default_bcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How they heard about us or referral email', max_length=255, null=True),
        ),
    ]
