# Generated by Django 6.0.3 on 2026-03-18 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bookingrequest_referral_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID or check number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.photographer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
