# Generated by Django 6.0.3 on 2026-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_photographerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Reason for manual completion if unpaid', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='invoice_logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sidebar_logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
