# Generated by Django 6.0.3 on 2026-03-18 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_bookingrequest_completion_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientshoot',
            name='stripe_payment_link',
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='photographer_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount owed to photographer for this shoot', max_digits=10),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='photographer_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already paid to photographer', max_digits=10),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='photographer_payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('billing', 'Billing Inquiry'), ('technical', 'Technical Issue'), ('booking', 'Booking Question'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
