# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_clientshoot_stripe_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientshoot',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Generated Stripe Checkout Session URL', max_length=1000, null=True),
        ),
    ]
