# Generated by Django 6.0.3 on 2026-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_clientshoot_stripe_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connected Account ID (Express/Custom)', max_length=100, null=True),
        ),
    ]
