# Generated by Django 6.0.2 on 2026-03-20 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_photographer_stripe_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Default reward amount for a successful referral', max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Amount to be awarded upon completion', max_digits=10),
        ),
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_credits', to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_issued', to='api.referral')),
            ],
        ),
    ]
