# Generated by Django 6.0.2 on 2026-03-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_globalsettings_referral_reward_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='referral_reward_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount ($)'), ('percentage', 'Percentage (%)')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Default reward amount or percentage', max_digits=10),
        ),
    ]
