# Generated by Django 6.0.2 on 2026-03-21 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_photographerrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Referral code entered by the client at booking', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='sqft',
            field=models.IntegerField(blank=True, help_text='Square footage of the property', null=True),
        ),
        migrations.AddField(
            model_name='clientshoot',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Referral code that was applied to this shoot', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
