# Generated by Django 6.0.2 on 2026-03-21 04:15

from django.db import migrations
import random
import string


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('api', 'UserProfile')

    def _gen_code(existing_codes):
        chars = string.ascii_uppercase + string.digits
        while True:
            code = 'KC' + ''.join(random.choices(chars, k=6))
            if code not in existing_codes:
                existing_codes.add(code)
                return code

    existing_codes = set(UserProfile.objects.values_list('referral_code', flat=True))
    profiles_to_create = []

    for user in User.objects.all():
        if not UserProfile.objects.filter(user=user).exists():
            profiles_to_create.append(
                UserProfile(user=user, referral_code=_gen_code(existing_codes))
            )

    UserProfile.objects.bulk_create(profiles_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_sqft_referral_fields'),
    ]

    operations = [
        migrations.RunPython(
            create_profiles_for_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
