# Generated by Django 6.0.2 on 2026-03-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_backfill_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
