# Generated by Django 6.0.2 on 2026-03-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='test_email_admin',
            field=models.EmailField(blank=True, help_text='Test recipient for admin emails', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='test_email_client',
            field=models.EmailField(blank=True, help_text='Test recipient for client emails', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='test_email_photographer',
            field=models.EmailField(blank=True, help_text='Test recipient for photographer emails', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='If enabled, all emails are redirected to test addresses instead of real recipients'),
        ),
    ]
