# Generated by Django 6.0.2 on 2026-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_email_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
